-- SELECTING ALL COLUMNS
SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

-- SELECTING SPECIFIC COLUMNS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

-- USING ARITHMETIC EXPRESSIONS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, SALARY+100, SALARY*1.1
FROM EMPLOYEES;

-- NULL VALUES
SELECT LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT, COMMISSION_PCT+10
FROM EMPLOYEES;

-- COLUMN ALIAS
SELECT LAST_NAME, FIRST_NAME AS NAME
FROM EMPLOYEES;

-- CONCATENATION
SELECT FIRST_NAME || ' ' || LAST_NAME "FULL NAME"
FROM EMPLOYEES;

SELECT FIRST_NAME || Q'[ WORK'S IN DEPARTMENT ]' || DEPARTMENT_ID
FROM EMPLOYEES;

-- DISTINCT
SELECT DISTINCT DEPARTMENT_ID, JOB_ID
FROM EMPLOYEES;

-- DESCRIBE
DESCRIBE EMPLOYEES;

DESC EMPLOYEES;

