-- OLD SYNTAX
-- CARTESIAN PRODUCT
SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME,
DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES, 
DEPARTMENTS
ORDER BY EMPLOYEE_ID;

-- EQUIJOIN / SIMPLE JOIN / INNER JOIN
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP, 
DEPARTMENTS DEPT
WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
AND EMP.DEPARTMENT_ID > 30
ORDER BY EMPLOYEE_ID;

SELECT
EMP.EMPLOYEE_ID, EMP.FIRST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME, 
DEPT.LOCATION_ID, LOC.CITY
FROM EMPLOYEES EMP,
DEPARTMENTS DEPT,
LOCATIONS LOC
WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
AND DEPT.LOCATION_ID = LOC.LOCATION_ID
ORDER BY EMPLOYEE_ID;

-- NONEQUIJOIN
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.SALARY, GRADES.GRADE_LEVEL
FROM EMPLOYEES EMP, JOB_GRADES GRADES
WHERE EMP.SALARY >= GRADES.LOWEST_SAL
AND EMP.SALARY <= GRADES.HIGHEST_SAL;

-- OUTER JOIN
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP, 
DEPARTMENTS DEPT
WHERE EMP.DEPARTMENT_ID(+) = DEPT.DEPARTMENT_ID;

SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP, 
DEPARTMENTS DEPT
WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID(+);

-- SELF JOIN
SELECT WORKER.EMPLOYEE_ID, WORKER.FIRST_NAME || ' ' || WORKER.LAST_NAME,
WORKER.MANAGER_ID, MANAGER.FIRST_NAME || ' ' || MANAGER.LAST_NAME
FROM EMPLOYEES WORKER, EMPLOYEES MANAGER
WHERE WORKER.MANAGER_ID = MANAGER.EMPLOYEE_ID
ORDER BY WORKER.EMPLOYEE_ID;


SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.DEPARTMENT_ID,
DEPT.DEPARTMENT_NAME, DEPT.LOCATION_ID, LOC.CITY, CONT.COUNTRY_NAME
FROM EMPLOYEES EMP,
DEPARTMENTS DEPT,
LOCATIONS LOC,
COUNTRIES CONT
WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID(+)
AND DEPT.LOCATION_ID = LOC.LOCATION_ID(+)
AND LOC.COUNTRY_ID = CONT.COUNTRY_ID(+)
AND SALARY > 2500;


-- 1999 SYNTAX
-- CROSS JOIN - SAME AS CARTESIAN JOIN
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES 
CROSS JOIN DEPARTMENTS
ORDER BY EMPLOYEE_ID;

-- NATURAL JOIN - JOINS COLUMNS THAT HAVE SAME NAME AND SAME DATATYPE
-- CANNOT PREFIX TABLE NAME IN MATCH COLUMN
SELECT DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME,
LOCATION_ID, LOC.CITY
FROM DEPARTMENTS DEPT
NATURAL JOIN LOCATIONS LOC
WHERE DEPARTMENT_ID > 20;

-- USING CLAUSE
-- CANNOT PREFIX TABLE NAME IN MATCH COLUMN
SELECT EMP.EMPLOYEE_ID, EMP.LAST_NAME, 
DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP 
JOIN DEPARTMENTS DEPT
USING (DEPARTMENT_ID)
WHERE EMPLOYEE_ID > 100;

-- ON CLAUSE
-- IS THE PREFERRED JOIN
-- PREFIX TABLE HAS TO BE USED
SELECT EMP.EMPLOYEE_ID, EMP.LAST_NAME, 
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP 
JOIN DEPARTMENTS DEPT
ON (EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID);

-- THREE TABLE JOINS
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME, LOC.CITY
FROM EMPLOYEES EMP 
JOIN DEPARTMENTS DEPT
ON (EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID)
JOIN LOCATIONS LOC
ON (DEPT.LOCATION_ID = LOC.LOCATION_ID);

-- LEFT/RIGHT/FULL OUTER JOINS
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP 
LEFT OUTER JOIN DEPARTMENTS DEPT
ON (EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID);

SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP 
RIGHT OUTER JOIN DEPARTMENTS DEPT
ON (EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID);

SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME,
DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP 
FULL OUTER JOIN DEPARTMENTS DEPT
ON (EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID);
