-- SEQUENCES
-- CAN AUTOMATICALLY GENERATE UNIQUE NUMBERS
-- IS A SHAREABLE OBJECT

-- USING DEFAULTS
CREATE SEQUENCE DEPT_SEQ;

CREATE SEQUENCE DEPT_S;

-- CHECK DETAILS
SELECT * 
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'DEPT_S';

-- TO USE THE SEQUENCE
CREATE TABLE DEPT_TEST_S
( DEPNO NUMBER PRIMARY KEY,
  DNAME VARCHAR2(100)
);

INSERT INTO DEPT_TEST_S (DEPNO, DNAME)
VALUES (DEPT_S.NEXTVAL, 'SALES');

INSERT INTO DEPT_TEST_S (DEPNO, DNAME)
VALUES (DEPT_S.NEXTVAL, 'OPERATIONS');

SELECT * FROM DEPT_TEST_S;

SELECT DEPT_S.CURRVAL FROM DUAL;

-- IF NEXTVAL USED, IT SHOWS AND SKIPS TO NEXT
SELECT DEPT_S.NEXTVAL FROM DUAL;

INSERT INTO DEPT_TEST_S (DEPNO, DNAME)
VALUES (DEPT_S.NEXTVAL, 'IT');

-- IT SHOWS A SKIP IN THE SEQUENCE
SELECT * FROM DEPT_TEST_S;

-- TO DROP SEQUENCE
DROP SEQUENCE DEPT_S1;

-----------------------
CREATE SEQUENCE DEPT_S1
START WITH 10
INCREMENT BY 20;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'DEPT_S1';

DELETE FROM DEPT_TEST_S;

INSERT INTO DEPT_TEST_S(DEPNO, DNAME)
VALUES (DEPT_S1.NEXTVAL, 'MARKETING');

INSERT INTO DEPT_TEST_S(DEPNO, DNAME)
VALUES (DEPT_S1.NEXTVAL, 'HELP DESK');

SELECT * FROM DEPT_TEST_S;

-----------------------
DELETE FROM DEPT_TEST_S;

CREATE SEQUENCE DEPT_S2
INCREMENT BY -5;

-- MAX VALUE -1, AND MIN VALUE -999.. (28 9 NINES)
SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'DEPT_S2';

INSERT INTO DEPT_TEST_S(DEPNO, DNAME)
VALUES (DEPT_S2.NEXTVAL, 'MARKETING');

INSERT INTO DEPT_TEST_S(DEPNO, DNAME)
VALUES (DEPT_S2.NEXTVAL, 'HELP DESK');

SELECT * FROM DEPT_TEST_S;

-----------------------
-- CAN ALSO USE IN UPDATE STATEMENT
UPDATE DEPT_TEST_S
SET DEPNO = DEPT_S2.NEXTVAL;

SELECT * FROM DEPT_TEST_S
ORDER BY 1;

-----------------------
-- WE CAN CREATE DEFAULT VALUE AS SEQUENCE IN CREATE TABLE
CREATE SEQUENCE EMP_S;

CREATE TABLE EMP_USESEQ
( EMPID NUMBER DEFAULT EMP_S.NEXTVAL PRIMARY KEY,
  NAME VARCHAR2(100),
  DEPTNO NUMBER
);

INSERT INTO EMP_USESEQ (NAME)
VALUES ('JAMES');

INSERT INTO EMP_USESEQ (NAME)
VALUES ('THOMAS');

SELECT * FROM EMP_USESEQ;

-----------------------
-- USING NEXTVAL AND CURRVAL TOGETHER
DELETE FROM DEPT_TEST_S;
DELETE FROM EMP_USESEQ;

DROP SEQUENCE DEPT_S;

CREATE SEQUENCE DEPT_S;

INSERT INTO DEPT_TEST_S (DEPNO, DNAME)
VALUES (DEPT_S.NEXTVAL, 'SUPPORT');

INSERT INTO EMP_USESEQ (NAME, DEPTNO)
VALUES ('ADAM', DEPT_S.CURRVAL);
INSERT INTO EMP_USESEQ (NAME, DEPTNO)
VALUES ('SAM', DEPT_S.CURRVAL);
INSERT INTO EMP_USESEQ (NAME, DEPTNO)
VALUES ('TOM', DEPT_S.CURRVAL);

SELECT * FROM DEPT_TEST_S;

SELECT * FROM EMP_USESEQ;

-----------------------
-- ALTERING THE SEQUENCE
SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'DEPT_S';

ALTER SEQUENCE DEPT_S
INCREMENT BY 100;

ALTER SEQUENCE DEPT_S
CACHE 30;

ALTER SEQUENCE DEPT_S
MAXVALUE 9999;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'DEPT_S';

-- CANNOT ALTER STARTING SEQUENCE NUMBER
ALTER SEQUENCE DEPT_S
START WITH 170;

-----------------------

CREATE SEQUENCE S_CYCLE
START WITH 1
INCREMENT BY 1
MAXVALUE 5
NOCACHE 
CYCLE;

SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;

SELECT S_CYCLE.NEXTVAL FROM DUAL;
-- REPEATS FROM 1
-- CYCLE SHOULD NOT BE USED IF THE SEQUENCE IS USED FOR PRIMARY KEY

-- NEW MAXVALUE LESS THAN CURRENT VALUE CANNOT BE SET

-- SYNONYMS
-- PRIVATE AND PUBLIC SYNONYMS, ALTERNATIVE NAME FOR OBJECT
DROP SYNONYM E;

CREATE SYNONYM E
FOR EMPLOYEES;

SELECT * FROM E;

SELECT *
FROM USER_SYNONYMS;

-- ANOTHER USER HAS TO TYPE HR.EMP
-- IF PUBLIC SYNONYM CREATED, THEN CAN USE SYNONYM DIRECTLY
CREATE PUBLIC SYNONYM EMPL FOR HR.EMPLOYEES; --INSUFFICIENT ACCESS

-----------------------
-- INDEXES



