-- DATA DEFINITION LANGUAGE STATEMENTS

CREATE TABLE EMP2
(EMPNO NUMBER);

--TABLE NAME CAN BE UPTO 128 CHARS FOR ORACLE 12.2

-- TABLE NAME CANNOT BE RESERVED WORD
CREATE TABLE SELECT
(EMPNO NUMBER);

-- DATA TYPES
CREATE TABLE TEST
( N1 NUMBER,
  N2 NUMBER(5,3));
  
INSERT INTO TEST (N1, N2)
VALUES           (20.25, 23.35534); -- HERE ORACLE ROUNDS THE DECIMAL TO 3 PLACES

INSERT INTO TEST
VALUES (100, 213.455); -- ERROR THROWN DUE TO NUMBER EXCEEDING PRECISION

-- CLOB RECOMMENDED INSTEAD OF LONG

-- CREATE TABLE
CREATE TABLE XX_EMP_TEST
( EMP_ID NUMBER,
  ENAME VARCHAR2(100),
  SALARY NUMBER(8,2),
  EMP_PIC BLOB
);

-- USING "" WILL MAKE IT CASE-SENSITIVE
-- AND HAS TO BE RETRIEVED USING DUOBLE QUOTES

-- USING DEFAULT
CREATE TABLE XX_EMP_TEST1
( EMP_ID NUMBER,
  ENAME VARCHAR2(100),
  START_DATE DATE DEFAULT SYSDATE
);

INSERT INTO XX_EMP_TEST1 (EMP_ID, ENAME)
VALUES (1, 'Nisu');

COMMIT;

SELECT * FROM XX_EMP_TEST1;

-- USING DICTIONARY TABLES
SELECT TABLE_NAME FROM USER_TABLES;

SELECT TABLE_NAME FROM ALL_TABLES
WHERE OWNER='HR';

-- CONSTRAINTS FOR CREATING TABLES
-- COLUMN LEVEL (TABLE LEVEL IS RECOMMENDED)
CREATE TABLE XX_EMP_COL_CONST
( EMP_ID NUMBER CONSTRAINT XX_EMP_COL_CONST_PK PRIMARY KEY,
  ENAME VARCHAR2(100) CONSTRAINT XX_EMP_COL_CONST_UK1 UNIQUE,
  SALARY NUMBER NOT NULL,
  GENDER CHAR(1) CONSTRAINT XX_EMP_COL_CONST_CHQ CHECK(GENDER IN ('M', 'F')),
  -- FOREIGN KEY SHOULD MATCH PRIMARY OR UNIQUE KEY IN ANOTHER TABLE
  DEPT_ID NUMBER CONSTRAINT XX_EMP_COL_CONST_FK1 REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

-- VIEWING CONSTRAINTS
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'XX_EMP_COL_CONST';

-- TABLE-LEVEL CONSTRAINTS
-- CAN MAKE PK HAVING MORE THAN ONE COLUMN
-- ALL CONSTRAINTS HAVE TO BE NAMED
CREATE TABLE XX_EMP_COL_CONST1
( EMP_ID1 NUMBER,
  EMP_ID2 NUMBER,
  ENAME VARCHAR2(100),
  SALARY NUMBER NOT NULL, -- CANNOT BE MADE AT TABLE LEVEL
  GENDER CHAR(1),
  DEPT_ID NUMBER,
  CONSTRAINT XX_EMP_COL_CONST1_PK PRIMARY KEY (EMP_ID1, EMP_ID2),
  CONSTRAINT XX_EMP_COL_CONST1_UK1 UNIQUE (ENAME),
  CONSTRAINT XX_EMP_COL_CONST1_CHQ CHECK (GENDER IN ('M', 'F')),
  CONSTRAINT XX_EMP_COL_CONST1_FK1 FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);
-- ONLY 1 PRIMARY KEY CAN BE IN A TABLE
-- NO SUCH LIMITATION FOR UNIQUE

-- ON DELETE CASCADE
