-- DISTINCT APPEARS ONCE, AT THE BEGINNING
-- CHAR DEFAULTS TO SIZE 1, IF NO SIZE SPECIFIED
-- NULLS COME LAST IN ASC ORDER, SAME OUTPUT AS SPECIFYING NULLS LAST IN ORDER BY

-- IF NOT REPLACEMENT GIVEN, REPLACE USES ''
SELECT REPLACE ('ALIBABA', 'AL') FROM DUAL;

-- TRIM ONLY REMOVES CHARACTERS FROM BEGINNING AND ENDING
-- DEFAULT REMOVAL IS SPACE
-- REMOVES MULTIPLE OCCURENCES OF CHARACTER FROM BEGINNING AND END
SELECT TRIM('KH' FROM 'KHAKHSDA') T FROM DUAL; -- ERROR SINCE TRIM SET SHOULD
-- ONLY HAVE ONE CHARACTER

-- MANY METHODS GIVE SAME OUTPUT
SELECT AVG(DECODE(DEPARTMENT_ID, 90, SALARY, NULL))
FROM EMPLOYEES;
-- CALCULATES AVERAGE SALARY FOR DEPARTMENT_ID 90

-- ALSO CAN BE DONE USING CASE

-- CANNOT MAKE CONSTRAINT FOR LONG COLUMN,OTHER THAN NOT NULL
-- CANNOT USE LONG COLUMN IN ORDER BY OR GROUP BY CLAUSE

-- TO_CHAR, ALL 5 BELOW GIVE SAME OUTPUT
SELECT TO_CHAR(1005.50, '9,999.99') FROM DUAL;
SELECT TO_CHAR(1005.50, '0,000.00') FROM DUAL;
SELECT TO_CHAR(1005.50, '0GOOODOO') FROM DUAL;
SELECT TO_CHAR(1005.50, '9G999D99') FROM DUAL;
SELECT TO_CHAR(1005.50, '0G909D99') FROM DUAL;

-- 0 FORCES 0 TO BE DISPLAYED
-- IF FM IS ADDED, SPACES ARE REMOVED
-- G AND D MUST BE USED TOGETHER

-- QUOTES Q' CAN USE ANY STARTING AND MATCHING ENDING CHARACTER


-- MATCH DATATYPE FOR NVL
SELECT EMPLOYEE_ID, NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, NVL(TO_CHAR(COMMISSION_PCT), 'NO COMM')
FROM EMPLOYEES;

-- FOR DECODE ALSO, MUST MATCH DATATYPES, EXCEPT FOR CASES IN WHICH IMPLICIT CONVERSION
-- IS POSSIBLE, SUCH AS FOR NUMBERS AND CHARACTERS

-- IMPLICIT CONVERSION FOR DATES
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE='17-JUN-03';

-- '17-jun-03', '17-jun-2003', '17-june-2003' ALSO WORK
-- '17-06-2003' GIVES ERROR

-- TO CREATE EMPTY TABLE, GIVE WHERE CONDITION THATS ALWAYS FALSE
-- ONLY STRUCTURE IS COPIED, WITHOUT ANY DATA
CREATE TABLE TABLE123
AS 
  SELECT * FROM EMPLOYEES
  WHERE 1=2;
  
SELECT * FROM EMPLOYEES
WHERE SALARY IS NOT NULL
ORDER BY SALARY DESC
FETCH FIRST 5 ROWS ONLY; -- OR FETCH NEXT 5 ROWS ONLY

-- NULL APPEARS FIRST IN DESCENDING ORDER
-- IN FETCH, 'ONLY' SHOULD NOT COME WITH 'WITH TIES'

-------------------------------------------------
-------------------------------------------------
-- NOTES

/*
DISTINCT CLAUSE IS USED ONLY ONCE, IN THE BEGINNING OF THE 
SQL STATEMENT.

VARCHAR2 HAS TO HAVE SIZE
CHAR CAN BE SET WITHOUT SIZE - TAKES DEFAULT SIZE 1, I.E. 1 CHARACTER

IN DEFAULT ORDER, (ASC), NULLS COME LAST
OR CAN BE GIVEN IN ORDER BY CLAUSE NULLS LAST. 
OTHER CLAUSE IS NULLS FIRST
 */
 
-- IF THE COLUMN IDENTIFIER HAS DOUBLE QUOTES, THEN IT HAS TO BE USED LATER
SELECT EMPLOYEE_ID || LAST_NAME "Test"
FROM EMPLOYEES
ORDER BY "Test";

-- WHILE USING REPLACE, IF NO REPLACEMENT STRING GIVEN, DEFAULT IS ""

SELECT REPLACE ('REPLACE', 'RE') FROM DUAL;

-- TRIM ONLY REMOVES CHARACTERS FROM THE BEGINNING AND THE END
-- DOES NOT REMOVE CHARS IN THE MIDDLE
-- CAN ONLY REMOVE 1 CHARACTER AT A TIME

-- LONG COLUMN CANNOT HAVE CONSTRAINT OTHER THAN NOT NULL, 
-- AND CANNOT BE USED IN ORDER BY OR GROUP BY

-- FORMATTING IN GROUP BY SHOULD BE THE SAME AS IN SELECT LIST

-- IN TO_CHAR, 0 FORCES 0 TO BE DISPLAYED
-- G AND D SHOULD BE USED TOGETHER FOR 1000 SEPARATOR AND DECIMAL

-- IN NVL, REPLACEMENT SHOULD HAVE SAME DATATYPE AS SPECIFIED COLUMN

-- SAME IN DECODE, I.E. USE TO_CHAR, WHEN THE REPLACEMENT VALUE IS A CHARACTER
-- THIS IS BASICALLY TO KEEP ALL THE VALUES IN A COLUMN THE SAME DATATYPE

-- IMPLICIT CONVERSION FOR DATE
-- JUN/JUNE, OR 03/2003 WORKS
-- 17-06-2003 DOESNT WORK
-- ONLY NUMBER-CHAR-NUMBER WORKS

-- FOR EMPTY TABLE CREATED WITH A STRUCTURE,
-- GIVE AN ALWAYS FALSE CONDITION IN WHERE I.E. 1=2

-- IN FETCH CLAUSE, ONLY AND WITH TIES DONT WORK TOGETHER
