
-- SET OPERATORS

SELECT *
FROM EMPLOYEES;

-- UNION REMOVES DUPLICATES
-- UNION ALL RETAINS DUPLICATES IN RETURNED RESULT

-- NOTE:
-- NAME OF COLUMNS NEED NOT BE IDENTICAL
-- NULL VALUES ARE NOT IGNORED IN MATCHING
-- BY DEFAULT OUTPUT SORTED IN ASCENDING ORDER

SELECT *
FROM JOB_HISTORY
WHERE EMPLOYEE_ID = 176;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176
UNION
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY
WHERE EMPLOYEE_ID = 176;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

-- UNION ALL
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;
-- UNION ALL IS NOT ORDERED

-- COLUMN HEADING IS ALWAYS TAKEN FROM 1ST QUERY

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

-- FOR MATCHING DUMMAY COLUMNS
SELECT EMPLOYEE_ID, JOB_ID, EMAIL
FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID, JOB_ID, TO_CHAR(NULL) EMAIL
FROM JOB_HISTORY;

-- ORDER BY CLAUSE ONLY USED AT END, AFTER UNION
