-- MANAGING DATA IN DIFFERENT TIMEZONES

SELECT INTERVAL '55-11' YEAR TO MONTH
FROM DUAL;

SELECT INTERVAL '555-11' YEAR(3) TO MONTH
FROM DUAL;
-- REQUIRES PRECISION IF GREATER THAN 2 DIGITS

SELECT INTERVAL '1000-11' YEAR(4) TO MONTH
FROM DUAL;

SELECT INTERVAL '350' MONTH
FROM DUAL;
-- CHANGES TO THE INTERVAL YEAR TO MONTH FORMAT

SELECT INTERVAL '10' YEAR
FROM DUAL;

SELECT INTERVAL '33 20:20:20' DAY TO SECOND
FROM DUAL;

SELECT INTERVAL '333 20:20:20' DAY(3) TO SECOND
FROM DUAL;
-- AGAIN MENTION SIZE IF MORE THAN 2 DIGITS

SELECT INTERVAL '500' HOUR
FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE, SYSDATE+10 FROM DUAL;

-- DATE AFTER 1 YEAR 2 MONTH FROM SYSDATE
SELECT SYSDATE, SYSDATE + INTERVAL '01-02' YEAR TO MONTH
FROM DUAL;

-- USING TO_YMINTERVAL
SELECT SYSDATE, SYSDATE + TO_YMINTERVAL('01-02')
FROM DUAL;

-- TO ADD 6 DAYS 2 HOURS TO SYSDATE
SELECT SYSDATE, SYSDATE + TO_DSINTERVAL('6 02:00:00')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY HH:MI:SS'),
TO_CHAR(SYSDATE + TO_DSINTERVAL('6 02:00:00'), 'DD-MM-YYYY HH:MI:SS')
FROM DUAL;

--------------------------------------------------------
-- EXTRACT, SIMILAR TO TO_CHAR(SYSDATE, 'YY')
SELECT
EXTRACT (YEAR FROM SYSDATE),
EXTRACT (MONTH FROM SYSDATE),
EXTRACT (DAY FROM SYSDATE)
FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE,
EXTRACT (YEAR FROM HIRE_DATE) HIRE_YEAR,
EXTRACT (MONTH FROM HIRE_DATE) HIRE_MONTH
FROM EMPLOYEES;

--------------------------------------------------------
-- TIMESTAMP
DROP TABLE DATE_TABLE;

CREATE TABLE DATE_TABLE
( DATE1 DATE,
  DATE2 TIMESTAMP,
  DATE3 TIMESTAMP WITH TIME ZONE
);

-- SYSDATE RETURNS TEH CURRENT DATE AND TIME FOR THE SERVER
-- CURRENT_TIMESTAMP RETURNS THE CURRENT DATE AND TIME FOR THE USER SESSION
-- USER SESSION CAN BE DIFFERENT THAN SERVERS
-- (TIMESTAMP WITH TIME ZONE)
INSERT INTO DATE_TABLE
VALUES (SYSDATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

SELECT * FROM DATE_TABLE;
-- CURRENT_TIMESTAMP ALSO CONTAINS FRACTIONAL SECONDS

SELECT TO_CHAR(DATE1, 'DD-MM-YYYY HH:MI:SS') DATE1, DATE2
FROM DATE_TABLE;
-- DATE1 ALSO CONTAINS TIME INFO, BUT NO FRACTIONAL SECONDS

--------------------------------------------------------
-- V$TIMEZONE_NAMES

SELECT * FROM V$TIMEZONE_NAMES
WHERE TZNAME LIKE '%America/Chicago%';

-- TIMEZONE CAN BE SET TO OFFSET OR REGION
SELECT DBTIMEZONE FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

SELECT CURRENT_DATE FROM DUAL;

-- CURRENTLY USER SESSION IS SAME AS SERVER SESSION, SO SYSDATE AND CURRENT_DATE
-- GIVE SAME DATE

-- RETURNS TIMESTAMP FOR USER SESSION
SELECT LOCALTIMESTAMP FROM DUAL;

-- TO CHANGE TIMEZONE FOR SESSION
ALTER SESSION SET TIME_ZONE = 'Asia/Amman';

SELECT SYSDATE, CURRENT_TIMESTAMP, LOCALTIMESTAMP FROM DUAL;

--------------------------------------------------------
-- TIMESTAMP WITH LOCAL TIME ZONE
DROP TABLE WEB_ORDER;

CREATE TABLE WEB_ORDER
(
  CUST_ID NUMBER,
  NAME VARCHAR2(100),
  ITEM VARCHAR2(100),
  DELIVERY_LOCATION VARCHAR2(100),
  ORDER_DATE TIMESTAMP WITH TIME ZONE,
  DELIVERY_PERIOD NUMBER,
  DELIVERY_DATE TIMESTAMP WITH LOCAL TIME ZONE
);

INSERT INTO WEB_ORDER VALUES (1, 'JIM', 'IPHONE', 'CHICAGO', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP + 3);

SELECT * FROM WEB_ORDER;

ALTER SESSION SET TIME_ZONE = 'Asia/Muscat';

SELECT * FROM WEB_ORDER;
-- THE TIME CHANGES ACCORDING TO WHAT TIMEZONE IS SET FOR THE USER

--------------------------------------------------------
-- TZ_OFFSET

SELECT TZ_OFFSET('Asia/Dubai'), TZ_OFFSET('America/Chicago')
FROM DUAL;

-- TO COMBINE TIMESTAMP AND TIMEZONE
SELECT FROM_TZ(TIMESTAMP '2000-03-6 08:00:00', 'Asia/Amman')
FROM DUAL;

-- TO_TIMESTAMP
SELECT TO_DATE('20-12-2016', 'DD-MM-YYYY')
FROM DUAL;

SELECT TO_TIMESTAMP('20-12-2016 12:10:33', 'DD-MM-YYYY HH:MI:SS')
FROM DUAL;


-------------------------------------------------
-------------------------------------------------
-- PRACTICE

SELECT INTERVAL '55-11' YEAR TO MONTH
FROM DUAL;

SELECT INTERVAL '555-11' YEAR(3) TO MONTH
FROM DUAL;

SELECT INTERVAL '350' MONTH
FROM DUAL;

SELECT INTERVAL '10' YEAR
FROM DUAL;

SELECT INTERVAL '1 01:01:01' DAY TO SECOND
FROM DUAL;

SELECT INTERVAL '111 01:01:01' DAY(3) TO SECOND
FROM DUAL;

SELECT INTERVAL '500' HOUR
FROM DUAL;

SELECT SYSDATE, SYSDATE + INTERVAL '01-02' YEAR TO MONTH
FROM DUAL;

SELECT SYSDATE, SYSDATE + TO_YMINTERVAL('01-02')
FROM DUAL;

SELECT SYSDATE, SYSDATE + TO_DSINTERVAL('01 01:01:01.1234')
FROM DUAL;

SELECT
EXTRACT (YEAR FROM SYSDATE),
EXTRACT (MONTH FROM SYSDATE),
EXTRACT (DAY FROM SYSDATE)
FROM DUAL;
-- SIMILAR FUNCTIONALITY TO TO_CHAR

SELECT * FROM DATE_TABLE;

DESC DATE_TABLE;

-- CURRENT _TIMESTAMP - TIMESTAMP WITH TIMEZONE FOR USER SESSION

SELECT * FROM V$TIMEZONE_NAMES;

SELECT DBTIMEZONE FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

SELECT CURRENT_DATE FROM DUAL;
-- RETURNS CURRENT DATE FOR USER SESSION

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT LOCALTIMESTAMP FROM DUAL;

ALTER SESSION SET TIME_ZONE = 'Asia/Amman';

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT LOCALTIMESTAMP FROM DUAL;

DESC WEB_ORDER;

SELECT * FROM WEB_ORDER;

SELECT TZ_OFFSET('Asia/Dubai') FROM DUAL;

-- FROM_TZ COMBINES TIMESTAMP AND TIMEZONE

-- TO_TIMESTAMP WORKS SIMILAR TO TO_DATE
SELECT TO_TIMESTAMP('20-12-2016 12:10:33', 'DD-MM-YYYY HH:MI:SS')
FROM DUAL;
