SELECT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES;

SELECT MAX(FIRST_NAME), MIN(HIRE_DATE)
FROM EMPLOYEES;

SELECT SUM(SALARY), ROUND(AVG(SALARY))
FROM EMPLOYEES;

SELECT COUNT(1)
FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES;

SELECT COUNT(NVL(COMMISSION_PCT, 0)) FROM EMPLOYEES;

-- LISTAGG FUNCTIONS
SELECT LISTAGG(FIRST_NAME, ', ')
       WITHIN GROUP (ORDER BY FIRST_NAME) "EMP LIST"
       FROM EMPLOYEES
       WHERE DEPARTMENT_ID = 30;
   
-- USING GROUP BY    
SELECT SUM(SALARY), ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY 1, 2;

-- CANNOT MAKE GROUPING BY ALIAS
-- CAN USE ALIAS WITH ORDERING
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) > 15000
ORDER BY DEPARTMENT_ID;

-- NESTING GROUP FUNCTIONS
SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) = (SELECT MAX(SUM(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);

