-- MANAGING DATA IN DIFFERENT TIMEZONES

SELECT INTERVAL '55-11' YEAR TO MONTH
FROM DUAL;

SELECT INTERVAL '555-11' YEAR(3) TO MONTH
FROM DUAL;
-- REQUIRES PRECISION IF GREATER THAN 2 DIGITS

SELECT INTERVAL '1000-11' YEAR(4) TO MONTH
FROM DUAL;

SELECT INTERVAL '350' MONTH
FROM DUAL;
-- CHANGES TO THE INTERVAL YEAR TO MONTH FORMAT

SELECT INTERVAL '10' YEAR
FROM DUAL;

SELECT INTERVAL '33 20:20:20' DAY TO SECOND
FROM DUAL;

SELECT INTERVAL '333 20:20:20' DAY(3) TO SECOND
FROM DUAL;
-- AGAIN MENTION SIZE IF MORE THAN 2 DIGITS

SELECT INTERVAL '500' HOUR
FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE, SYSDATE+10 FROM DUAL;

-- DATE AFTER 1 YEAR 2 MONTH FROM SYSDATE
SELECT SYSDATE, SYSDATE + INTERVAL '01-02' YEAR TO MONTH
FROM DUAL;

-- USING TO_YMINTERVAL
SELECT SYSDATE, SYSDATE + TO_YMINTERVAL('01-02')
FROM DUAL;

-- TO ADD 6 DAYS 2 HOURS TO SYSDATE
SELECT SYSDATE, SYSDATE + TO_DSINTERVAL('6 02:00:00')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY HH:MI:SS'),
TO_CHAR(SYSDATE + TO_DSINTERVAL('6 02:00:00'), 'DD-MM-YYYY HH:MI:SS')
FROM DUAL;



