-- SELECTING ALL COLUMNS
SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

-- SELECTING SPECIFIC COLUMNS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

-- USING ARITHMETIC EXPRESSIONS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, SALARY+100, SALARY*1.1
FROM EMPLOYEES;

-- NULL VALUES
SELECT LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT, COMMISSION_PCT+10
FROM EMPLOYEES;

-- COLUMN ALIAS
SELECT LAST_NAME, FIRST_NAME AS NAME
FROM EMPLOYEES;

-- CONCATENATION
SELECT FIRST_NAME || ' ' || LAST_NAME "FULL NAME"
FROM EMPLOYEES;

SELECT FIRST_NAME || Q'[ WORK'S IN DEPARTMENT ]' || DEPARTMENT_ID
FROM EMPLOYEES;

-- DISTINCT
SELECT DISTINCT DEPARTMENT_ID, JOB_ID
FROM EMPLOYEES;

-- DESCRIBE
DESCRIBE EMPLOYEES;

DESC EMPLOYEES;

-----------------------------------------
-- PRACTICE
SELECT *
FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

-- ALL RESERVED WORDS APPEAR IN BLUE COLOR

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM EMPLOYEES;
-- SELECT STATEMENT IS CASE INSENSITIVE

SELECT * FROM DEPARTMENTS;

SELECT COUNT(1)
FROM DEPARTMENTS;

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

-----------------------------------------
-- ARITHMETIC EXPRESSIONS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY * 1.1
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY * 100 "Incremented_Salary"
FROM EMPLOYEES;
-- '' SINGLE QUOTES GIVE ERROR FOR THE ABOVE STATEMENT

SELECT LAST_NAME, JOB_ID, COMMISSION_PCT
FROM EMPLOYEES;
-- NULL VALUE IS UNAVAILABLE OR UNASSIGNED

-- ARITHMETIC EXPRESSIONS CONTAINING A NULL VALUE EVALUATE TO NULL
SELECT LAST_NAME, JOB_ID, COMMISSION_PCT, COMMISSION_PCT + 10
FROM EMPLOYEES;

SELECT LAST_NAME, JOB_ID, COMMISSION_PCT, COMMISSION_PCT + 10
FROM EMPLOYEES
ORDER BY COMMISSION_PCT;

-----------------------------------------
-- ALIAS
-- RENAMES COLUMN HEADING
SELECT LAST_NAME, FIRST_NAME AS FN, LAST_NAME "AN eXAMPLE"
FROM EMPLOYEES;

SELECT FIRST_NAME ||" " || LAST_NAME
FROM EMPLOYEES;
-- HERE "" GIVES ERROR

SELECT FIRST_NAME ||' WORKS IN DEPARTMENT '|| DEPARTMENT_ID
FROM EMPLOYEES;

-- TO GIVE APOSTROPHE ETC INSIDE, GIVE Q FOR QUOTE
SELECT FIRST_NAME ||Q'[ WORK'S IN DEPARTMENT ]'|| DEPARTMENT_ID
FROM EMPLOYEES;
-- CAN CHOOSE [], {}, () ETC

-- DISTINCT
SELECT DISTINCT DEPARTMENT_ID, LAST_NAME
FROM EMPLOYEES;
-- DISTINCT ONLY APPEARS ONCE AT THE BEGINNING
-- CAN USE FOR MANY COMBINATIONS OF COLUMNS

-- DESCRIBE
DESC EMPLOYEES;
DESCRIBE EMPLOYEES;

-----------------------------------------
-- IMPORTANT NOTES
/*
Select statement is a projection. 
Keywords cannot be abbreviated or split across lines
Best Practices:
Clauses usually on separate lines
Indents to enhance readability
SQL*Plus requries semicolon at end of each SQL statement
*/























