SELECT * FROM SESSION_PRIVS;

CREATE TABLE EMP
( EMPID NUMBER CONSTRAINT EMP_PK PRIMARY KEY,
  ENAME VARCHAR2(100)
);

INSERT INTO EMP
VALUES (1, 'NISU');

ALTER TABLE EMP
ADD (SALARY NUMBER);

SELECT * FROM EMP;

CREATE SEQUENCE EMP_S;

CREATE INDEX ENAME_IND ON EMP (ENAME);

CREATE OR REPLACE VIEW EMP_V
AS
SELECT EMPID, ENAME
FROM EMP;

SELECT * FROM HR.EMPLOYEES;

-- CAN USE ONLY 'EMPLOYEES' IF A PUBLIC SYNONYM HAD BEEN CREATED
SELECT * FROM ALL_SYNONYMS
WHERE TABLE_NAME = 'EMPLOYEES';

-- UPDATE PRIVILEGES
UPDATE HR.EMPLOYEES
SET DEPARTMENT_ID = NULL
WHERE EMPLOYEE_ID = 1;
-- ERROR - HAS ONLY BEEN GIVEN UPDATE PRIVILEGE ON SALARY

UPDATE HR.EMPLOYEES
SET SALARY = 500
WHERE EMPLOYEE_ID = 1;
-- WORKS

SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 1;

----------------------------------------------------
-- DICTIONARY TABLES
SELECT * FROM SESSION_PRIVS;

SELECT * FROM USER_SYS_PRIVS;

-- SHOW ALL TABLE PRIVILEGES
SELECT * FROM USER_TAB_PRIVS_RECD
ORDER BY 2;

SELECT * FROM USER_COL_PRIVS_RECD;

-- GRANTING PRIVILEGES TO OWNED OBJECTS
GRANT SELECT ON EMP TO HR;

-- SHOWS ALL PRIVILEGES GRANTED
SELECT * FROM USER_TAB_PRIVS_MADE;

GRANT UPDATE (ENAME) ON EMP TO HR;

SELECT * FROM USER_COL_PRIVS_MADE;

