-- SUBSTITUTION VARIABLES
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_NUM;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = &ENAME;

SELECT *
FROM &EMPLOYEES
WHERE FIRST_NAME = '&ENAME';

-- DEFINE/UNDEFINE
DEFINE EMPLOYEE_NUM = 200;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_NUM;

UNDEFINE EMPLOYEE_NUM;

-- ACCEPT/PROMPT
ACCEPT DEPT_ID PROMPT 'PLEASE ENTER DEPT ID'
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = &DEPT_ID;

UNDEFINE DEPT_ID;

ACCEPT EMP_FROM PROMPT 'ENTER EMPLOYEE FROM';
ACCEPT EMP_TO PROMPT 'ENTER EMPLOYEE TO';
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN &EMP_FROM AND &EMP_TO;

UNDEFINE EMP_FROM;
UNDEFINE EMP_TO;

-- &&
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = &&P;

UNDEFINE P;

SELECT EMPLOYEE_ID, LAST_NAME, &&COLUMN_NAME
FROM EMPLOYEES
ORDER BY &COLUMN_NAME;

UNDEFINE COLUMN_NAME;

SET DEFINE OFF;
SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '%&t%';
-- ESCAPE FUNCTIONALITY DOES NOT WORK IN ABOVE SITUATION

