-- SUBSTITUTION VARIABLES
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_NUM;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = &ENAME;

SELECT *
FROM &EMPLOYEES
WHERE FIRST_NAME = '&ENAME';

-- DEFINE/UNDEFINE
DEFINE EMPLOYEE_NUM = 200;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_NUM;

UNDEFINE EMPLOYEE_NUM;

-- ACCEPT/PROMPT
ACCEPT DEPT_ID PROMPT 'PLEASE ENTER DEPT ID'
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = &DEPT_ID;

UNDEFINE DEPT_ID;

ACCEPT EMP_FROM PROMPT 'ENTER EMPLOYEE FROM';
ACCEPT EMP_TO PROMPT 'ENTER EMPLOYEE TO';
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN &EMP_FROM AND &EMP_TO;

UNDEFINE EMP_FROM;
UNDEFINE EMP_TO;

-- &&
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = &&P;

UNDEFINE P;

SELECT EMPLOYEE_ID, LAST_NAME, &&COLUMN_NAME
FROM EMPLOYEES
ORDER BY &COLUMN_NAME;

UNDEFINE COLUMN_NAME;

SET DEFINE OFF;
SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '%&t%';
-- ESCAPE FUNCTIONALITY DOES NOT WORK IN ABOVE SITUATION


-----------------------------------------------------
-- PRACTICE
--SUBSTITUTION VARIABLES FOR USE IN WHERE CONDITIONS

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_NUM;
-- FOR SINGLE & VARIABLE DISCARDED AFTER USE

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = '&ENAME';

-- OR

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = &ENAME;

-- CAN SPECIFY MULTIPLE SUBSTITUTION VARIABLES
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, &COLUMN_NAME
FROM EMPLOYEES
WHERE &CONDITION
ORDER BY &ORDER_COLUMN;

-- DEFINE CAN BE USED TO SET A VARIABLE FOR THE WHOLE SESSION
DEFINE EMPLOYEE_NUM = 200;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_NUM;
-- VARIABLE ALREADY DEFINED AND HAS VALUE

UNDEFINE EMPLOYEE_NUM;
-- REMOVES THE VARIABLE

-- ACCEPT/PROMPT
-- NEW WAY TO ACCEPT VARIABLE
ACCEPT DEPT_ID PROMPT 'PLEASE ENTER DEPT ID';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = &DEPT_ID;

UNDEFINE DEPT_ID;

-- USING &&
--USED TO ASSIGN AND DEFINE VALUE AT THE SAME TIME, SO IT CAN BE REUSED
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID=&&DEPT_ID;

-- CAN THEN UNDEFINE IT
UNDEFINE DEPT_ID;

SELECT EMPLOYEE_ID, &&COLUMN_NAME
FROM EMPLOYEES
ORDER BY &COLUMN_NAME;

SELECT *
FROM EMPLOYEES
ORDER BY &COLUMN_NAME;

UNDEFINE COLUMN_NAME;

-- VERIFY COMMAND
-- TOGGLES DISPLAY OF SUBSTITUTION VARIABLE
SET VERIFY ON
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &E_NUM;

-- WHEN WE DONT WANT TO USE & AS A SUBSTITUTION VARIABLE
-- USE SET DEFINE OFF

SET DEFINE OFF;

-- MAINLY USED FOR DATA MIGRATION
SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '%&t%';

