-- ADDING & MANAGING CONSTRAINTS

DROP TABLE EMP2;

CREATE TABLE EMP2
AS
  SELECT * FROM EMPLOYEES;

CREATE TABLE DEPT3
AS
  SELECT * FROM DEPARTMENTS;
  
-- ONLY NOT NULL CONSTRAINTS COPIED
DESC EMP2;

-----------------------------------------------
-- ADDING PRIMARY KEY
SELECT *
FROM EMP2;

ALTER TABLE EMP2
MODIFY EMPLOYEE_ID PRIMARY KEY;

-- CAN SEE THE ADDED CONSTRAINT, TYPE P
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP2';

-- REMOVE LAST ADDED CONSTRAINT
ALTER TABLE EMP2
DROP CONSTRAINT &CONS;

-- ADD WITH NAME
ALTER TABLE EMP2
ADD CONSTRAINT EMP2_PK PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE DEPT3
ADD CONSTRAINT DEPT3_PK PRIMARY KEY (DEPARTMENT_ID);

-----------------------------------------------
-- ADDING FOREIGN KEY
-- METHOD 1
ALTER TABLE EMP2
MODIFY DEPARTMENT_ID REFERENCES DEPT3 (DEPARTMENT_ID);

-- METHOD 2
ALTER TABLE EMP2
ADD CONSTRAINT EMP_FK_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPT3 (DEPARTMENT_ID);

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP2';

-----------------------------------------------
-- ADDING NOT NULL CONSTRAINTS
