SELECT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES;

SELECT MAX(FIRST_NAME), MIN(HIRE_DATE)
FROM EMPLOYEES;

SELECT SUM(SALARY), ROUND(AVG(SALARY))
FROM EMPLOYEES;

SELECT COUNT(1)
FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES;

SELECT COUNT(NVL(COMMISSION_PCT, 0)) FROM EMPLOYEES;

-- LISTAGG FUNCTIONS
SELECT LISTAGG(FIRST_NAME, ', ')
       WITHIN GROUP (ORDER BY FIRST_NAME) "EMP LIST"
       FROM EMPLOYEES
       WHERE DEPARTMENT_ID = 30;
   
-- USING GROUP BY    
SELECT SUM(SALARY), ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY 1, 2;

-- CANNOT MAKE GROUPING BY ALIAS
-- CAN USE ALIAS WITH ORDERING
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) > 15000
ORDER BY DEPARTMENT_ID;

-- NESTING GROUP FUNCTIONS
SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) = (SELECT MAX(SUM(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);

-----------------------------------------------
-----------------------------------------------
-- PRACTICE

-- MULTI-ROW FUNCTIONS RETURN ONE RESULT FOR GROUPS OF ROWS
-- COUNT IGNORES NULL VALUES IF A FIELD IS GIVEN, BUT COUNT(*) COUNTS THE NUMBER
-- OF ROWS, INCLUDING NULLS
-- ALL THE GROUP FUNCTIONS IGNORE NULL VALUES

SELECT SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT MAX(SALARY), MIN(SALARY), MAX(LAST_NAME), MAX(HIRE_DATE)
FROM EMPLOYEES;

SELECT SUM(SALARY), ROUND(AVG(SALARY), 2)
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES;

-- IF FIELD GIVEN IN COUNT, NULL VALUES ARE NOT COUNTED
SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT COUNT (DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES;

-- HANDLE NULL VALUES USING FUNCTIONS
SELECT COUNT(NVL(COMMISSION_PCT, 0))
FROM EMPLOYEES;

-- COUNTING WITH CONDITIONS
SELECT COUNT(*)
FROM EMPLOYEES
WHERE HIRE_DATE < '11-NOV-03';

-- GROUP BY
SELECT JOB_ID, ROUND(AVG(SALARY)) AVRG
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING ROUND(AVG(SALARY)) > 10000
ORDER BY AVRG DESC
FETCH FIRST 10 ROWS ONLY;

-- GROUP BY CANNOT BE DONE USING ALIAS
-- ORDERING CAN BE DONE BY ALIAS

-- 2 GROUP FUNCTIONS CAN BE NESTED
SELECT MAX(SUM(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 1;
